apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.binding.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  {{- $mysql_user := default (randAlphaNum 8) .Values.user }}
  {{- $mysql_password := default (randAlphaNum 16) .Values.password }}
  {{- $mysql_root_password := default (randAlphaNum 16) .Values.rootPassword }}
  mysql-user: {{ $mysql_user | b64enc | quote }}
  mysql-password: {{ $mysql_password | b64enc | quote }}
  mysql-root-password: {{ $mysql_root_password | b64enc | quote }}
  binding: {{ cat `{"uri":"mysql://` $mysql_user `:` $mysql_password `@` .Release.Name `-` .Values.service.name `:` .Values.service.externalPort `/` .Values.dbname `" }` | nospace | b64enc | quote }}