#!/bin/bash

MASTER_HOST=$1
MASTER_IP=$2
MASTER_PORT=3306
MASTER_USER=${REPL_USER}
MASTER_PASSWORD=${REPL_PASSWD}

# add master to /etc/hosts
echo "${MASTER_IP} ${MASTER_HOST}" >> /etc/hosts

mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "CHANGE MASTER TO MASTER_HOST='${MASTER_IP}', MASTER_PORT=${MASTER_PORT}, MASTER_USER='${MASTER_USER}', MASTER_PASSWORD='${MASTER_PASSWORD}', MASTER_AUTO_POSITION=1;"

mysql -uroot -p${MYSQL_ROOT_PASSWORD} -e "START SLAVE;"
