#!/bin/bash

DOCKER_CMD="docker"
SITE_MASK=0
SITE="dal09"
MASTER_CONTAINER_NAME=mysql-master-${SITE}
SLAVE_CONTAINER_NAME=mysql-slave-${SITE}

MASTER_SERVER_ID=$((1 << $SITE_MASK))
SLAVE_SERVER_ID=$(((1 << $SITE_MASK) + 1))




